services:
  db:
    image: postgres:15-alpine
    container_name: engnet_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: engnet_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    container_name: engnet_frontend
    ports:
      - "3001:3000" # Você acessará o site em http://localhost:3001
    environment:
      # URL que o navegador (cliente) vai usar para falar com o backend exposto na sua máquina
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      
      # URL que o Next.js (servidor interno) vai usar para falar com o backend diretamente pela rede do Docker
      - NEXT_PUBLIC_SERVER_API_URL=http://backend:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env

volumes:
  db_data: